# config/services/services_pms.yaml
#
# SOLO servicios del módulo PMS.
# Los parámetros (incl. `calendars_pms`) viven en services_parameters_pms.yaml.
services:

    _defaults:
        autowire: true
        autoconfigure: true

    App\Pms\:
        resource: '../../src/Pms/'
        exclude:
            - '../../src/Pms/Dto/'
            - '../../src/Pms/Entity/'
            - '../../src/Pms/Tarifa/Dto/'

    # =========================
    # controllers del módulo Pms
    # (fuera de src/Controller/)
    # =========================
    App\Pms\Controller\:
        resource: '../../src/Pms/Controller/'
        autowire: true
        autoconfigure: true
        tags:
          - 'controller.service_arguments'

    # =========================
    # Reglas por instanceof lo estouy poniendo como tag directo al archivo
    # =========================
    #_instanceof:
    #    App\Pms\Service\Cron\CronJobInterface:
    #        tags:
    #          - 'app.cron_job'
