# config/services/services_util.yaml
services:

    _defaults:
        autowire: true
        autoconfigure: true

    # =========================
    # controllers del módulo Pms
    # (fuera de src/Controller/)
    # =========================
    App\Util\Controller\:
        resource: '../../src/Util/Controller/'
        autowire: true
        autoconfigure: true
        tags:
            - 'controller.service_arguments'

