api_platform:
    title: Hello API Platform
    version: 1.0.0

    # 🔥 AQUI ESTA LA MAGIA: Le decimos dónde buscar los #[ApiResource]
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Pms/Entity'
            - '%kernel.project_dir%/src/Message/Entity'
            - '%kernel.project_dir%/src/Travel/Entity'
            - '%kernel.project_dir%/src/Cotizacion/Entity'
            # Descomenta estas líneas si luego quieres exponer APIs de estos módulos:
            # - '%kernel.project_dir%/src/Exchange/Entity'


    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        multipart: ['multipart/form-data']