<?php

namespace App\Repository;
use App\Entity\UserUser;
use Symfony\Component\HttpKernel\Exception\HttpException;

/**
 * CotcomponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotizacionCotcomponenteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCalendarAceptado($data)
    {
        if(!$data['user'] instanceof UserUser) {
            throw new HttpException(500, 'El dato de usuario no es instancia de la clase App\Entity\UserUser.');
        }else{
            $user = $data['user'];
        }

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('cc')
            ->from('App\Entity\CotizacionCotcomponente', 'cc')
            ->innerJoin('cc.cotservicio', 'cs')
            ->innerJoin('cs.cotizacion', 'cot')
            ->where('cc.fechahorafin >= :firstDate AND cc.fechahorainicio <= :lastDate')
            ->andWhere('cot.estadocotizacion = 3');


        $qb->setParameter('firstDate', $data['from'])
            ->setParameter('lastDate', $data['to']);

        return $qb;

    }

    public function findCalendarAceptadoEfectuado($data)
    {
        if(!$data['user'] instanceof UserUser) {
            throw new HttpException(500, 'El dato de usuario no es instancia de la clase App\Entity\UserUser.');
        }else{
            $user = $data['user'];
        }

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('cc')
            ->from('App\Entity\CotizacionCotcomponente', 'cc')
            ->innerJoin('cc.cotservicio', 'cs')
            ->innerJoin('cs.cotizacion', 'cot')
            ->where('cc.fechahorafin >= :firstDate AND cc.fechahorainicio <= :lastDate')
            ->andWhere('cot.estadocotizacion IN (:estados)');


        $qb->setParameter('firstDate', $data['from'])
            ->setParameter('lastDate', $data['to'])
            ->setParameter('estados', [3, 4]);

        return $qb;

    }
}
