<?php

namespace App\Repository;
use App\Entity\UserUser;
use Symfony\Component\HttpKernel\Exception\HttpException;

/**
 * ReservaReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaReservaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCalendarTodas($data)
    {

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('rr')
            ->from('App\Entity\ReservaReserva', 'rr')
            //->innerJoin('cs.cotizacion', 'cot')
            ->where('rr.fechahorafin >= :firstDate AND rr.fechahorainicio <= :lastDate');
            //->andWhere('cot.estadocotizacion = 3');


        $qb->setParameter('firstDate', $data['from'])
            ->setParameter('lastDate', $data['to']);

        /** @var UserUser|null $user */
        $user = $data['user'] ?? null;
        if ($user instanceof UserUser) {
            // Ejemplos (ajusta a tu modelo):
            /*
            $depId = $user->getDependencia()?->getId();
            if ($depId !== null && $depId !== 1) {
                $qb->andWhere('IDENTITY(me.dependencia) = :depId')
                    ->setParameter('depId', $depId);
            }

            $conductorId = $user->getConductor()?->getId();
            if ($conductorId !== null) {
                $qb->andWhere('IDENTITY(me.conductor) = :conductorId')
                    ->setParameter('conductorId', $conductorId);
            }
            */
        }

        return $qb;

    }

    public function findCalendarNoCanceladas($data)
    {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('rr')
            ->from('App\Entity\ReservaReserva', 'rr')
            //->innerJoin('cs.cotizacion', 'cot')
            ->where('rr.fechahorafin >= :firstDate AND rr.fechahorainicio <= :lastDate')
            ->andWhere($qb->expr()->notIn('rr.estado', [3]));


        $qb->setParameter('firstDate', $data['from'])
            ->setParameter('lastDate', $data['to']);

        /** @var UserUser|null $user */
        $user = $data['user'] ?? null;
        if ($user instanceof UserUser) {
            // Ejemplos (ajusta a tu modelo):
            /*
            $depId = $user->getDependencia()?->getId();
            if ($depId !== null && $depId !== 1) {
                $qb->andWhere('IDENTITY(me.dependencia) = :depId')
                    ->setParameter('depId', $depId);
            }

            $conductorId = $user->getConductor()?->getId();
            if ($conductorId !== null) {
                $qb->andWhere('IDENTITY(me.conductor) = :conductorId')
                    ->setParameter('conductorId', $conductorId);
            }
            */
        }

        return $qb;

    }

}
