<?php

namespace App\Repository;
use App\Entity\UserUser;
use Symfony\Component\HttpKernel\Exception\HttpException;

/**
 * ReservaReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaReservaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCalendarTodas($data)
    {
        if (!$data['user'] instanceof UserUser) {
            throw new HttpException(500, 'El dato de usuario no es instancia de la clase App\Entity\UserUser.');
        } else {
            $user = $data['user'];
        }

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('rr')
            ->from('App\Entity\ReservaReserva', 'rr')
            //->innerJoin('cs.cotizacion', 'cot')
            ->where('rr.fechahorafin >= :firstDate AND rr.fechahorainicio <= :lastDate');
            //->andWhere('cot.estadocotizacion = 3');


        $qb->setParameter('firstDate', $data['from'])
            ->setParameter('lastDate', $data['to']);

        return $qb;

    }

    public function findCalendarNoCanceladas($data)
    {
        if (!$data['user'] instanceof UserUser) {
            throw new HttpException(500, 'El dato de usuario no es instancia de la clase App\Entity\UserUser.');
        } else {
            $user = $data['user'];
        }

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('rr')
            ->from('App\Entity\ReservaReserva', 'rr')
            //->innerJoin('cs.cotizacion', 'cot')
            ->where('rr.fechahorafin >= :firstDate AND rr.fechahorainicio <= :lastDate')
            ->andWhere($qb->expr()->notIn('rr.estado', [3]));


        $qb->setParameter('firstDate', $data['from'])
            ->setParameter('lastDate', $data['to']);

        return $qb;

    }

}
