# config/services.yaml
imports:

    - { resource: 'services/services_parameters.yaml' }
    - { resource: 'services/services_parameters_pms.yaml' }
    - { resource: 'services/services_core.yaml' }

    - { resource: 'services/services_calendar.yaml' }

#debe declararse antes de exchange
    - { resource: 'services/services_agent.yaml' }
    - { resource: 'services/services_pms.yaml' }
    - { resource: 'services/services_message.yaml' }
    - { resource: 'services/services_api.yaml' }
    - { resource: 'services/services_front.yaml' }
    - { resource: 'services/services_pax.yaml' }
    - { resource: 'services/services_util.yaml' }
    - { resource: 'services/services_travel.yaml' }
    - { resource: 'services/services_cotizacion.yaml' }
    - { resource: 'services/services_operacion.yaml' }
    - { resource: 'services/services_finanzas.yaml' }
    - { resource: 'services/services_domotica.yaml' }


    - { resource: 'services/services_exchange.yaml' }

    - { resource: 'services/services_panel.yaml' }
