<?php

namespace App\Oweb\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArchivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainArchivoRepository extends EntityRepository{
    public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }
}
